import { Link } from "react-router-dom";

const Footer = () => {
  return (
    <div>
      <div className="container my-5">
        <footer className="text-center text-lg-start text-color">
          <div className="container-fluid p-4 pb-0">
            <section>
              <div className="row">
                <div className="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 className="text-uppercase text-color">Why Carbon Credit Trading?</h5>
                  <p>
                    • Reduce your carbon footprint by purchasing carbon credits from others.<br />
                    • Earn money by selling excess carbon credits generated by your sustainability efforts.<br />
                    • Support climate action and advance sustainable development goals.
                  </p>
                </div>
                <div className="col-lg-6 col-md-12 mb-4 mb-md-0">
                  <h5 className="text-uppercase text-color">How It Works</h5>
                  <ol>
                    <li>Sign up for a Carbon Credit Trading account.</li>
                    <li>Browse carbon credit listings from sellers.</li>
                    <li>Place bids on listings or create your own listing to sell carbon credits.</li>
                    <li>Finalize the transaction and start trading carbon credits!</li>
                  </ol>
                </div>
              </div>
            </section>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Footer;
